### PR TITLE
Triple audit logging fix (#1995)

### LINKED ISSUE #1995: [BUG] Triple logging of audit messages
**What is the bug?**
OpenSearch log contains extra audit messages:
```
[2022-08-05T08:03:52,622][INFO ][sgaudit                  ] [opensearch-1] {"audit_cluster_name":"opensearch","audit_transport_headers":{"_system_index_access_allowed":"false"},"audit_node_name":"opensearch-1","audit_trace_task_id":"wlV1pg8FSlWuVvCZgniL8w:104","audit_transport_request_type":"GetIndexRequest","audit_category":"INDEX_EVENT","audit_request_origin":"REST","audit_node_id":"wlV1pg8FSlWuVvCZgniL8w","audit_request_layer":"TRANSPORT","@timestamp":"2022-08-05T08:03:52.595+00:00","audit_format_version":4,"audit_request_remote_address":"192.168.160.1","audit_request_privilege":"indices:admin/get","audit_node_host_address":"192.168.160.2","audit_request_effective_user":"admin","audit_trace_indices":[".opendistro_security"],"audit_trace_resolved_indices":[".opendistro_security"],"audit_node_host_name":"192.168.160.2"}
[2022-08-05T08:03:52,623][WARN ][sgaudit                  ] [opensearch-1] {"audit_cluster_name":"opensearch","audit_transport_headers":{"_system_index_access_allowed":"false"},"audit_node_name":"opensearch-1","audit_trace_task_id":"wlV1pg8FSlWuVvCZgniL8w:104","audit_transport_request_type":"GetIndexRequest","audit_category":"INDEX_EVENT","audit_request_origin":"REST","audit_node_id":"wlV1pg8FSlWuVvCZgniL8w","audit_request_layer":"TRANSPORT","@timestamp":"2022-08-05T08:03:52.595+00:00","audit_format_version":4,"audit_request_remote_address":"192.168.160.1","audit_request_privilege":"indices:admin/get","audit_node_host_address":"192.168.160.2","audit_request_effective_user":"admin","audit_trace_indices":[".opendistro_security"],"audit_trace_resolved_indices":[".opendistro_security"],"audit_node_host_name":"192.168.160.2"}
[2022-08-05T08:03:52,623][ERROR][sgaudit                  ] [opensearch-1] {"audit_cluster_name":"opensearch","audit_transport_headers":{"_system_index_access_allowed":"false"},"audit_node_name":"opensearch-1","audit_trace_task_id":"wlV1pg8FSlWuVvCZgniL8w:104","audit_transport_request_type":"GetIndexRequest","audit_category":"INDEX_EVENT","audit_request_origin":"REST","audit_node_id":"wlV1pg8FSlWuVvCZgniL8w","audit_request_layer":"TRANSPORT","@timestamp":"2022-08-05T08:03:52.595+00:00","audit_format_version":4,"audit_request_remote_address":"192.168.160.1","audit_request_privilege":"indices:admin/get","audit_node_host_address":"192.168.160.2","audit_request_effective_user":"admin","audit_trace_indices":[".opendistro_security"],"audit_trace_resolved_indices":[".opendistro_security"],"audit_node_host_name":"192.168.160.2"}
```

**How can one reproduce the bug?**
1. Perform the following request:
   ```
   curl -XGET http://localhost:19200/.opendistro_security
   ```
   to get information about `.opendistro_security` index.
2. Check log messages

**What is the expected behavior?**
The log must only contain one audit message instead of three:
```
[2022-08-05T08:03:52,622][INFO ][sgaudit                  ] [opensearch-1] {"audit_cluster_name":"opensearch","audit_transport_headers":{"_system_index_access_allowed":"false"},"audit_node_name":"opensearch-1","audit_trace_task_id":"wlV1pg8FSlWuVvCZgniL8w:104","audit_transport_request_type":"GetIndexRequest","audit_category":"INDEX_EVENT","audit_request_origin":"REST","audit_node_id":"wlV1pg8FSlWuVvCZgniL8w","audit_request_layer":"TRANSPORT","@timestamp":"2022-08-05T08:03:52.595+00:00","audit_format_version":4,"audit_request_remote_address":"192.168.160.1","audit_request_privilege":"indices:admin/get","audit_node_host_address":"192.168.160.2","audit_request_effective_user":"admin","audit_trace_indices":[".opendistro_security"],"audit_trace_resolved_indices":[".opendistro_security"],"audit_node_host_name":"192.168.160.2"}
```

**What is your host/environment?**
- OS: Linux
- Version: 1.3.4
- Plugins: OpenSearch Security

**Do you have any screenshots?**
n/a

**Do you have any additional context?**
The bug is the incorrect usage of `switch-case` construction in `org.opensearch.security.auditlog.sink.Log4JSink` class:
```
private boolean isLogLevelEnabled(Logger logger, Level level) {
    boolean isEnabled = false;
    switch(level.toString()) {
        case "TRACE": isEnabled = logger.isTraceEnabled();
        case "DEBUG": isEnabled = logger.isDebugEnabled();
        case "INFO": isEnabled = logger.isInfoEnabled();
        case "WARN": isEnabled = logger.isWarnEnabled();
        case "ERROR": isEnabled = logger.isErrorEnabled();
    }
    return isEnabled;
}

private void logAtLevel(Logger logger, Level level, String msg) {
    switch(level.toString()) {
        case "TRACE": logger.trace(msg);
        case "DEBUG": logger.debug(msg);
        case "INFO": logger.info(msg);
        case "WARN": logger.warn(msg);
        case "ERROR": logger.error(msg);
    }
}
```
This code does not contain `break`/`return` keywords to stop switching.
It seems the changes were not rolled back in PR: [Switch to log4j logger](https://github.com/opensearch-project/security/pull/1751).

### PR DESCRIPTION
**Pull request by jchipmunk**
Revert some changes introduced by https://github.com/opensearch-project/security/pull/1563 to correct work with log4j.

Signed-off-by: Andrey Pustovetov <andrey.pustovetov@gmail.com>

### Description
[Describe what this change achieves]
* Category: Bug fix
* Why these changes are required?
When I execute `GET` request to `.opendistro_security` index, I see three audit messages in the logs instead of one.

### Issues Resolved
#1995

### Testing
I manually checked the changes by doing `GET` request to the index and checking the logs.

### Check List
- [ ] ~~New functionality includes testing~~
- [ ] ~~New functionality has been documented~~
- [ X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/main/java/org/opensearch/security/auditlog/sink/Log4JSink.java [hunk 1]
```diff
@@ -30,40 +30,17 @@ public Log4JSink(final String name, final Settings settings, final String settin
...
-
     public boolean doStore(final AuditMessage msg) {
         if(enabled) {
-            logAtLevel(auditLogger, logLevel, msg.toJson());
+            auditLogger.log(logLevel, msg.toJson());
         }
         return true;
     }
-
-    private boolean isLogLevelEnabled(Logger logger, Level level) {
```
Comment (peternied) [inline src/main/java/org/opensearch/security/auditlog/sink/Log4JSink.java:48]: Thank you for removing these extraneous functions

**Review by peternied — COMMENTED** [review]
Reading and rereading this code I'm not sure what was causing the triple logging which has been fixed with this PR, could you provide more details about what wasn't working before?

**Comment by jchipmunk** [comment]
> 



> Reading and rereading this code I'm not sure what was causing the triple logging which has been fixed with this PR, could you provide more details about what wasn't working before?

The bug is the incorrect usage of `switch-case` construction in Java:
```
private void logAtLevel(Logger logger, Level level, String msg) {
    switch(level.toString()) {
        case "TRACE": logger.trace(msg);
        case "DEBUG": logger.debug(msg);
        case "INFO": logger.info(msg);
        case "WARN": logger.warn(msg);
        case "ERROR": logger.error(msg);
    }
}
```
This code does not contain `break`/`return` keywords to stop switching so the message with `INFO` logging level will be logged three times:
```
logger.info(msg);
logger.warn(msg);
logger.error(msg);
```

**Comment by peternied** [comment]
@jchipmunk 🤣 Thank you for that gem, you have made my day.

**Review by peternied — APPROVED** [review]

**Comment by peternied** [comment]
Looks like CI got stuck when a new OpenSearch 2.2.0 build was being created, re-running the failed CI jobs

**Review by cwperks — APPROVED** [review]

**Comment by jchipmunk** [comment]
@peternied, thanks for reviewing the PR

Is it possible to backport the changes to the branch 1.3?

**Comment by peternied** [comment]
@jchipmunk I've created the backport #2026, we will continue the discussion over there.
