### PR TITLE
Fixed IllegalArgumentException when building stateful index privileges

### LINKED ISSUE #5216: [BUG]
**What is the bug?**
Since we upgrade to opensearch 2.19.1 we are getting a lot of logs with exceptions like following lines.

```
Mar 26 08:44:28 systemd-opensearch-opensearch1-n4: [2025-03-26T08:44:28,829][ERROR][o.o.s.p.ActionPrivileges ] [opensearch1-n4] Unexpected exception while processing role: usr_tenant_loadbalancer_search
Mar 26 08:44:28 systemd-opensearch-opensearch1-n4: Ignoring role.
Mar 26 08:44:28 systemd-opensearch-opensearch1-n4: java.lang.IllegalArgumentException: Invalid key .ds-production-ci-general-000033; not present in keySuperSet
Mar 26 08:44:28 systemd-opensearch-opensearch1-n4:         at com.selectivem.collections.CompactMapGroupBuilder$MapBuilder.get(CompactMapGroupBuilder.java:139) ~[special-collections-complete-1.4.0.jar:?]
Mar 26 08:44:28 systemd-opensearch-opensearch1-n4:         at org.opensearch.security.privileges.ActionPrivileges$StatefulIndexPrivileges.<init>(ActionPrivileges.java:1029) [opensearch-security-2.19.1.0.jar:2.19.1.0]
Mar 26 08:44:28 systemd-opensearch-opensearch1-n4:         at org.opensearch.security.privileges.ActionPrivileges.updateStatefulIndexPrivileges(ActionPrivileges.java:247) [opensearch-security-2.19.1.0.jar:2.19.1.0]
Mar 26 08:44:28 systemd-opensearch-opensearch1-n4:         at org.opensearch.security.privileges.ActionPrivileges.updateClusterStateMetadata(ActionPrivileges.java:265) [opensearch-security-2.19.1.0.jar:2.19.1.0]
Mar 26 08:44:28 systemd-opensearch-opensearch1-n4:         at org.opensearch.security.privileges.ClusterStateMetadataDependentPrivileges.lambda$updateClusterStateMetadataAsync$0(ClusterStateMetadataDependentPrivileges.java:68) [opensearch-security-2.19.1.0.jar:2.19.1.0]
Mar 26 08:44:28 systemd-opensearch-opensearch1-n4:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) [?:?]
Mar 26 08:44:28 systemd-opensearch-opensearch1-n4:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) [?:?]
Mar 26 08:44:28 systemd-opensearch-opensearch1-n4:         at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:955) [opensearch-2.19.1.jar:2.19.1]
Mar 26 08:44:28 systemd-opensearch-opensearch1-n4:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]
Mar 26 08:44:28 systemd-opensearch-opensearch1-n4:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]
Mar 26 08:44:28 systemd-opensearch-opensearch1-n4:         at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

Following is the configured role. We are mainly using aliases as index patterns.
```
{
  "usr_tenant_loadbalancer_search": {
    "reserved": false,
    "hidden": false,
    "cluster_permissions": [],
    "index_permissions": [
      {
        "index_patterns": [
          "hc_production-ci-general-read",
          "hc_production-ci-ingress-read"
        ],
        "fls": [],
        "masked_fields": [],
        "allowed_actions": [
          "read",
          "get",
          "search",
          "indices:admin/mappings/get",
          "indices:monitor/settings/get",
          "indices:monitor/stats"
        ]
      }
    ],
    "tenant_permissions": [],
    "static": false
  }
}
```

**What is the expected behavior?**
Not to see any exceptions.

**What is your host/environment?**
We are running opensearch via podman quadlet.
 - OS: Ubuntu 24.04
 - Version 2.19.1
 - Plugins
 ```
ingest-attachment                    2.19.1
opensearch-alerting                  2.19.1.0
opensearch-anomaly-detection         2.19.1.0
opensearch-asynchronous-search       2.19.1.0
opensearch-cross-cluster-replication 2.19.1.0
opensearch-custom-codecs             2.19.1.0
opensearch-flow-framework            2.19.1.0
opensearch-geospatial                2.19.1.0
opensearch-index-management          2.19.1.0
opensearch-job-scheduler             2.19.1.0
opensearch-knn                       2.19.1.0
opensearch-ltr                       2.19.1.0
opensearch-ml                        2.19.1.0
opensearch-neural-search             2.19.1.0
opensearch-notifications             2.19.1.0
opensearch-notifications-core        2.19.1.0
opensearch-observability             2.19.1.0
opensearch-reports-scheduler         2.19.1.0
opensearch-security                  2.19.1.0
opensearch-security-analytics        2.19.1.0
opensearch-skills                    2.19.1.0
opensearch-sql                       2.19.1.0
opensearch-system-templates          2.19.1.0
prometheus-exporter                  2.19.1.0
query-insights                       2.19.1.0
repository-s3                        2.19.1
```

### PR DESCRIPTION
**Pull request by nibix**
### Description

This fixes the issue reported in #5216. In the case that a cluster has aliases defined on backing indices of data streams, the creation of the stateful rule would fail with an `IllegalArgumentException`. 

This is because data stream backing indices are not supposed to be included in the stateful index privilege object. Via the aliases, however, they sneaked in anyway. We are now filtering these indices out.

This is mostly just a cosmetic problem as privilege evaluation will continue via slower fall back code paths. However, the logs will show an `IllegalArgumentException` stack trace for each update of the index meta data on the cluster.

* Category
  * Bugfix
* Why these changes are required?
  * Fixes log spam
* What is the old behavior before changes and new behavior after changes?
  * No behavioral change
### Issues Resolved

Fixes #5216

### Testing

- The unit test `aliasesOnDataStreamBackingIndices` was added to cover this case

### Check List
- [x] New functionality includes testing
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/security/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/main/java/org/opensearch/security/privileges/ActionPrivileges.java [hunk 1]
```diff
@@ -1026,7 +1026,23 @@ static class StatefulIndexPrivileges {
...
+                                            // because these indices get a separate treatment. However, these indices
+                                            // might still appear as member indices of aliases. Trying to add these
+                                            // to the SubSetBuilder indexToRoles would result in an IllegalArgumentException
+                                            // because the subIndex will not be part of the super set.
+                                            if (indices.containsKey(subIndexName)) {
+                                                indexToRoles.get(subIndexName).add(roleName);
+                                            } else {
+                                                log.debug(
+                                                    "Ignoring member index {} of alias {}. This is usually the case because the index is closed or a data stream backing index.",
+                                                    subIndexName,
```
Comment (shikharj05) [inline src/main/java/org/opensearch/security/privileges/ActionPrivileges.java:1042]: Thanks for the quick work @nibix ! Should we open a corresponding GH issue to support data streams with optimized evaluation?

Comment (nibix) [reply src/main/java/org/opensearch/security/privileges/ActionPrivileges.java:1042]: It is already supported; it is just that the code in question is not responsible for supporting it.

Comment (nibix) [reply src/main/java/org/opensearch/security/privileges/ActionPrivileges.java:1042]: When designing the feature, we had the challenge that the data structures must not grow too big. Especially data streams, however, have the habit of creating many backing indices under the hood. For that reason, the code contains a special case for backing indices. Backing indices are not added as member to the data structures. Rather, only an entry for the data stream itself is created. As backing indices have a back reference to the data stream, it is easy to deduct the privileges for the backing indices from the data stream.

**Review by cwperks — APPROVED** [review]
Thank you for the quick work on this @nibix and confirming that the fallback is working as intended.

File: src/main/java/org/opensearch/security/privileges/ActionPrivileges.java (hunk 1 above)
Comment (shikharj05) [reply src/main/java/org/opensearch/security/privileges/ActionPrivileges.java:1042]: Thanks as always @nibix !

**Review by shikharj05 — APPROVED** [review]

File: src/main/java/org/opensearch/security/privileges/ActionPrivileges.java [hunk 2]
```diff
@@ -1026,7 +1026,23 @@ static class StatefulIndexPrivileges {
...
+                                                    indicesEntry.getKey()
+                                                );
+                                            }
                                         }
                                     }
```
Comment (shikharj05) [inline src/main/java/org/opensearch/security/privileges/ActionPrivileges.java:1048]: commenting here to check on below- 
```
catch (Exception e) {
                    log.error("Unexpected exception while processing role: {}\nIgnoring role.", entry.getKey(), e);
                }
```

Is the silent failure okay? i.e. would this always fallback to legacy style of evaluation or can it lead to leaks?

Comment (nibix) [reply src/main/java/org/opensearch/security/privileges/ActionPrivileges.java:1048]: We have in the ActionPrivileges a strict deny-by-default policy. If we are skipping a role, this has only the effect that users might have fewer privileges.

**Review by willyborankin — APPROVED** [review]

**Comment by nibix** [comment]
@Jakob3xD The comment regarding the failed backport is confusing, but this has been already backported to 2.19: #5235
