### PR TITLE
[BUG-2556] Add new DLS filtering test

### LINKED ISSUE #2556: [BUG] Can't use multiple roles with DLS permissions on the same Index
**What is the bug?**
When a user is bound to two roles using DLS permissions on the same index, only one DLS policy is taken into account.
Each role with DLS permissions works _independently_ as expected, but they won't combine in the typical additive fashion.

**How can one reproduce the bug?**
1: create a "global" role with READ on index pattern * and the following DLS:
  ```
  {
    "bool": {
      "must_not": {
        "match": {
          "sensitive": true
        }
      }
    }
  }
  ```
2: create a higher privileged role on any indices (example-*) with some catch-all DLS policy:
  ```
  {
    "bool": {
      "must": {
        "match_all": {}
      }
    }
  }
  ```
3: Query that example-* index pattern using the a User bound to both roles. Observe that you will not have any logs that contains `"sensitive": true`

**What is the expected behavior?**
The policies to be additive (combine each DLS statement in an OR query)

**What is your host/environment?**
 - Provider: AWS Opensearch
 - Version: OpenSearch 2.3
 - Plugins: unsure

**Do you have any additional context?**
Add any other context about the problem.

The codebase seems to indicate selection of a single arbitrary DLS policy for each index:
https://github.com/opensearch-project/security/blob/ca4d7528851ea94d936181f86428a25f0c59c8c1/src/main/java/org/opensearch/security/configuration/DlsFilterLevelActionHandler.java#L405

https://github.com/opensearch-project/security/blob/ca4d7528851ea94d936181f86428a25f0c59c8c1/src/main/java/org/opensearch/security/support/SecurityUtils.java#L98

Same issue [described here](https://forum.opensearch.org/t/how-is-dls-applied-when-user-has-multiple-roles/2946)

### PR DESCRIPTION
**Pull request by prabhask5**
### Description
This PR adds a new DLS filtering test that checks for the union of different dls settings related to different roles attached to the same user.

* Category (Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation)
Enhancement

* Why these changes are required?
These tests were previously not included, which makes testing bugs including the one in #2556 difficult. Adding this test makes it easy to recreate these bugs if they appear in the future. Additionally the data in these test cases matches the examples provided in the bug case so these tests were also used to determine if the bug in the ticket is actually happening. Since these two tests pass, I personally don't think this bug is reproducible.

* What is the old behavior before changes and new behavior after changes?
A new test should increase code coverage.

### Issues Resolved
#2556 

Is this a backport? If so, please add backport PR # and/or commits #
No

### Testing
Added new test

### Check List
- [x] New functionality includes testing
- [x] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by prabhask5** [comment]
@peternied @scrawfor99 @cwperks Ready for review!

File: src/integrationTest/java/org/opensearch/security/DlsIntegrationTests.java [hunk 1]
```diff
@@ -158,6 +164,56 @@ public class DlsIntegrationTests {
                 .on("*")
         );
 
+    /**
+     * Test role 1 for DLS filtering with two (non)overlapping roles. This role imposes a filter where the user can only access documents where the sensitive field is false. This role is applied at a higher level for all index patterns.
+     */
+    static final TestSecurityConfig.Role TEST_ROLE_ONE = new TestSecurityConfig.Role("test_role_1").clusterPermissions(
```
Comment (scrawfor99) [inline src/integrationTest/java/org/opensearch/security/DlsIntegrationTests.java:170]: Nit: What do you think about renaming the roles so that they say what they do similar to below with the music tests? I.e ROLE_NON_SENSITIVE_ONLY

**Review by scrawfor99 — COMMENTED** [review]
Really awesome work here. Just one comment about potential naming and then a typo I caught. Thanks for all your work

File: src/integrationTest/java/org/opensearch/security/DlsIntegrationTests.java [hunk 2]
```diff
@@ -517,4 +597,110 @@ public void testAggregateAndComputeStarRatings() throws IOException {
...
+                )
+            );
+        }
+
+        try (RestHighLevelClient restHighLevelClient = cluster.getRestHighLevelClient(TEST_UNION_OF_NONOVERLAPPING_ROLES_USER)) {
+            SearchRequest searchRequest = new SearchRequest(UNION_TEST_INDEX_NAME);
+            SearchResponse searchResponse = restHighLevelClient.search(searchRequest, DEFAULT);
+
+            assertThat(searchResponse, isSuccessfulSearchResponse());
+            assertThat(searchResponse, numberOfTotalHitsIsEqualTo(9));
```
Comment (DarshitChanpura) [inline src/integrationTest/java/org/opensearch/security/DlsIntegrationTests.java:689]: This code can be cleaned up to allow re-usability.

```suggestion
            assertSearchResponseHitsEqualTo(9);
```

and a function:
```
private void assertSearchResponseHitsEqualTo(int hits) {
        SearchRequest searchRequest = new SearchRequest(UNION_TEST_INDEX_NAME);
        SearchResponse searchResponse = restHighLevelClient.search(searchRequest, DEFAULT);

        assertThat(searchResponse, isSuccessfulSearchResponse());
        assertThat(searchResponse, numberOfTotalHitsIsEqualTo(hits));
}
```

Comment (prabhask5) [reply src/integrationTest/java/org/opensearch/security/DlsIntegrationTests.java:689]: searchResponse is used in the two checks below this so I'll keep them in the main function but I'll make that helper function to be used in future tests

**Comment by prabhask5** [comment]
@scrawfor99 @DarshitChanpura Ready for review! I think I added all the requested changes.

**Review by scrawfor99 — APPROVED** [review]
Looks great to me! Thanks a bunch @prabhask5

**Review by DarshitChanpura — APPROVED** [review]
LGTM!
