### PR TITLE
Fix IllegalArgumentException when resolved indices are empty

### LINKED ISSUE #5794: [BUG] java.lang.IllegalArgumentException: Must contain at least one column and at least one row (got []/[indices:monitor/recovery])
**What is the bug?**

If the security plugin 2.19.3.0 is enabled, information about ongoing and completed shard recoveries cannot be obtained via the `/_cat/recovery` endpoint because all indices are closed (have been closed manually).

The request fails with:
`java.lang.IllegalArgumentException: Must contain at least one column and at least one row (got []/[indices:monitor/recovery])`

On 2.17 the same works fine, and setting `plugins.security.privileges_evaluation.use_legacy_impl=true` solves the issue. 

**How can one reproduce the bug?**

- Start 3-node cluster with a security plugin 2.19.3.0 enabled
- Close all indices
- curl `/_cat/recovery`

The resolution for such a request yelds an empty list:
```
        Set<String> resolvedIndicesSet = resolvedIndices.getAllIndicesResolved(
            context.getClusterStateSupplier(),
            context.getIndexNameExpressionResolver());

        // resolvedIndicesSet - empty list
```

The request fails with the stacktrace in logs:

```
Unexpected exception java.lang.IllegalArgumentException: Must contain at least one column and at least one row (got []/[indices:monitor/recovery])
java.lang.IllegalArgumentException: Must contain at least one column and at least one row (got []/[indices:monitor/recovery])
        at com.selectivem.collections.CheckTableImpl.create(CheckTableImpl.java:81) ~[special-collections-complete-1.4.0.jar:?]
        at com.selectivem.collections.CheckTable.create(CheckTable.java:75) ~[special-collections-complete-1.4.0.jar:?]
        at org.opensearch.security.privileges.ActionPrivileges.hasIndexPrivilege(ActionPrivileges.java:210) ~[opensearch-security-2.19.3.0.jar:2.19.3.0]
        at org.opensearch.security.privileges.PrivilegesEvaluatorImpl.evaluate(PrivilegesEvaluatorImpl.java:603) ~[opensearch-security-2.19.3.0.jar:2.19.3.0]
        at org.opensearch.security.filter.SecurityFilter.apply0(SecurityFilter.java:377) [opensearch-security-2.19.3.0.jar:2.19.3.0]
        at org.opensearch.security.filter.SecurityFilter.apply(SecurityFilter.java:166) [opensearch-security-2.19.3.0.jar:2.19.3.0]
        at org.opensearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:218) [opensearch-2.19.3.jar:2.19.3]
        at org.opensearch.action.support.TransportAction.execute(TransportAction.java:190) [opensearch-2.19.3.jar:2.19.3]
        at org.opensearch.action.support.TransportAction.execute(TransportAction.java:109) [opensearch-2.19.3.jar:2.19.3]

```

**What is the expected behavior?**

The request completes fine.

**What is your host/environment?**
 - OS: Linux dev40 6.8.5-301.fc40.aarch64
 - OpenSearch 2.19.3
 - opensearch security plugin 2.19.3.0

**Possible solution**

The problem is probably in the following [condition in the ActionPrivileges](https://github.com/opensearch-project/security/blob/2.19/src/main/java/org/opensearch/security/privileges/ActionPrivileges.java#L185) , when is actully not applied when `isLocalAll == true` (request containing `"*"`).

The solution could be as simple as checking the resolved indices before passing them to the `CheckTable`:

```
    if (resolvedLocalIndices.isEmpty()) {
        return PrivilegesEvaluatorResponse.ok();
    }
```

Please, let me know what do you think and if I need prepare a fix for that.

### PR DESCRIPTION
**Pull request by Mmuzaf**
## Description

This PR fixes an `IllegalArgumentException` that occured when resolved indices are empty in the `PrivilegesEvaluator`. This issue occurs when all indices are closed (e.g., during cluster maintenance) and operations like `_cat/recovery` are executed. 

## Category

Bug fix

## Why these changes are required?

When all indices in a cluster are closed, certain operations like `_cat/recovery` can still be valid and should be authorized. However, when `getAllIndicesResolved()` returns an empty set, the code was attempting to create a `CheckTable` with an empty collection, which throws an `IllegalArgumentException`. 

This prevents valid operations from being authorized when indices are closed.

## What is the old behavior before changes and new behavior after changes?

**Old behavior:**
- When all indices were closed and `getAllIndicesResolved()` returned an empty set, the code would attempt to create a `CheckTable` with an empty collection and throw an exception.

**New behavior:**
- When `getAllIndicesResolved()` returns an empty set allow operations to proceed
- Operations like `_cat/recovery` now succeed when users have the appropriate permissions, even when all indices are closed

## Issues Resolved

Resolves #5794

## Is this a backport?

No

## Do these changes introduce new permission(s) to be displayed in the static dropdown on the front-end?

No

## Testing

- Added unit test `hasIndexPrivilegeEmptyResolvedIndices()`
- Added integration test `IndexAuthorizationWithClosedIndicesIntTests`

### Manual Testing

- Verified that `_cat/recovery` and similar operations work correctly when all indices are closed

## Check List

- [x] New functionality includes testing
- [x] New functionality has been documented (CHANGELOG.md updated)
- [x] New Roles/Permissions have a corresponding security dashboards plugin PR (N/A - no new permissions)
- [x] API changes companion pull request created (N/A - no API changes)
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/security/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by nibix** [comment]
@Mmuzaf 

Thanks for the update! On Friday, I will be quite busy with other stuff, so I will only have time to take a closer look on Monday. 

> if there are no indices, and users do not have any indices priveleges for the action at all, such requests should be also forbidden.

We need to take a closer look at this:

- I *believe* that this behavior is the case also for all other index actions. If this is a fundamentally exposed behavior, we will likely have to mantain backwards compatiblity
- For remote index operations, such a behavior is actually required. It is even possible that there are coordinator clusters with no local indices at all. In such cases it is expected that no local privileges are required.

Of course, this is a discussable topic - at the moment, we are working on some fundamental behavior changes (see #3905, #5367 and #5399 ; I also need to write an updated RFC soon). Feel invited to discuss there.

**Comment by nibix** [comment]
@Mmuzaf 

Sorry for the late reply, was just too busy :-(

That looks generally very good to me! Yet, I think we need to briefly reflect on this:

>  if there are no indices, and users do not have any indices priveleges for the action at all, such requests should be also forbidden

If I see this correctly, this would have the following effect:

- Doing a `GET /a*,remote_cluster:b/_search` would be allowed even if the local user has no local privileges for search if `a*` does not match any indices. That's due to the condition here: https://github.com/opensearch-project/security/blob/91a70978ae4f01e53bb2e4540a81464756cfe978/src/main/java/org/opensearch/security/privileges/actionlevel/RuntimeOptimizedActionPrivileges.java#L94
- Doing a `GET /*,remote_cluster:b/_search` would be then forbidden however as this goes through the new gate `this.index.hasAnyIndexPrivilegeForAction(context, actions)`

This is a kind of inconsistent behavior which we should avoid IMHO (even though it might be a case that seldomly happens in the real word). 

For now, I would propose not to do the `hasAnyIndexPrivilegeForAction()` check to stay in sync with the existing behavior. 

At the moment, we are busy on revising the index authorization behavior, see #5814. We could use that chance and implement the behavior change in that go. Feel invited to have a look there and comment :)

@cwperks wdyt?

File: src/integrationTest/java/org/opensearch/security/privileges/actionlevel/RoleBasedActionPrivilegesTest.java [hunk 1]
```diff
@@ -1034,6 +1035,30 @@ public void statefulDisabled() throws Exception {
...
         }
+
+        /**
+         * Tests the behavior of hasIndexPrivilege when the resolved indices are empty.
+         * @throws Exception If failed.
+         */
+        @Test
+        public void hasIndexPrivilegeEmptyResolvedIndices() throws Exception {
+            SecurityDynamicConfiguration<RoleV7> roles = SecurityDynamicConfiguration.fromYaml(
+                "test_role:\n"
```
Comment (cwperks) [inline src/integrationTest/java/org/opensearch/security/privileges/actionlevel/RoleBasedActionPrivilegesTest.java:1046]: nit: I think we can use java text blocks to define multi-line strings.

**Comment by cwperks** [comment]
When all indices are closed is it possible to call `_cat/recovery?expand_wildcards=all`?

I'm also wondering if it makes sense to respond with a warning telling the caller that it could not resolve to indices.

**Comment by cwperks** [comment]
@Mmuzaf @nibix @willyborankin do you think we should respond with a warning when we cannot resolve to indices? I believe https://github.com/opensearch-project/OpenSearch/blob/799fb9bf46b1eb823f26f72e368f70a5675bf88f/server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java#L651-L662 shows an example of how it can be done.

**Review by nibix — DISMISSED** [review]

**Review by nibix — APPROVED** [review]
re-approved
